version: '3'
services:
  tool_portainer:
    container_name: 'godocker_portainer'
    image: portainer/portainer
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data portainer/portainer
  app:  
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - database
  database:
    container_name: database
    image: postgres:10.3
    restart: always
    volumes:
      - pgdata:/var/lib/postgres
    environment:
        - POSTGRES_DB=app_database
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin@123
    ports:
        - 5432:5432
volumes:
  pgdata:

